name: demo_flutter
description: A simple to demo Flutter

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  fluttery: 0.0.8
  fluttery_audio: 0.0.3
  http: ^0.12.0+2
  url_launcher: ^3.0.1
  image_picker: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/bg_uit.jpg
    - images/logo_uit.png
    - images/clap.png
    - images/clap_border.png
    - images/sparkles.png
    - images/ic_home.png
    - images/ic_menu.png
    - images/ic_seat.png
    - images/ic_red_circle.png
    - images/chair_top.png
    - images/chair_bottom.png
    - images/table_big_pink.png
    - images/table_big_green.png
    - images/table_small_yellow.png
    - images/table_small_green.png
    - images/ic_add.png
    - images/ic_book.png
    - images/ic_clock.png
    - images/ic_cancel.png
    - images/flan.png
    - images/curry.png
    - images/salad.png
    - images/chicken.png
    - images/duck.png
    - images/pizza.png
    - images/ic_cake.png
    - images/ic_car.png
    - images/ic_coffee.png
    - images/ic_cook.png
    - images/ic_restaurant.png
    - images/shadow_white.png
    - images/ic_white_circle.png
    - images/ic_add_circle.png
    - images/ic_remove_circle.png
    - images/ic_avatar.png
    - images/ic_camera.png
    - images/ic_mercury.png
    - images/ic_venus.png
    - images/ic_mars.png
    - images/ic_jupiter.png
    - images/ic_saturn.png
    - images/ic_uranus.png
    - images/ic_neptune.png
    - images/ic_moon.png
    - images/like.gif
    - images/love.gif
    - images/haha.gif
    - images/wow.gif
    - images/sad.gif
    - images/angry.gif
    - images/ic_like.png
    - images/ic_like_fill.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
